project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - 1-2-encoding/1-2-3-character-encoding/course-design.qmd
    - 1-2-encoding/1-2-3-character-encoding/demo-lab-teacher.qmd
    - 1-2-encoding/1-2-3-character-encoding/demo-lab-student.qmd
    - 1-2-encoding/1-2-3-character-encoding/slides.qmd
    - 1-2-encoding/1-2-3-image-encoding/course-design.qmd
    - 1-2-encoding/1-2-3-image-encoding-v2/course-design.qmd
    - 1-2-encoding/1-2-3-image-encoding-v2/slides.qmd

website:
  title: "shtick"
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: 1-2-encoding/1-2-3-character-encoding/course-design.qmd
        text: 字符编码
      - href: 1-2-encoding/1-2-3-character-encoding/slides.qmd
        text: Slides
      - href: 1-2-encoding/1-2-3-character-encoding/demo-lab-teacher.qmd
        text: Teacher Demo
      - href: 1-2-encoding/1-2-3-character-encoding/demo-lab-student.qmd
        text: Student Demo
      - href: 1-2-encoding/1-2-3-image-encoding/course-design.qmd
        text: 图像编码

format:
  html:
    toc: true
    code-copy: true

execute:
  warning: false
